export enum Fonts {
    ppns_bl = "poppins_black",
    ppns_bl_it = "poppins_black_italic",
    ppns_bo = "poppins_bold",
    ppns_bo_it = "poppins_bold_italic",
    ppns_xbl = "poppins_extra_bold",
    ppns_xbl_it = "poppins_extra_bold_italic",
    ppns_xlg = "poppins_extra_light",
    ppns_xlg_it = "poppins_extra_light_italic",
    ppns_it = "poppins_italic",
    ppns_lg = "poppins_light",
    ppns_lg_it = "poppins_light_italic",
    ppns_md = "poppins_medium",
    ppns_md_it = "poppins_medium_italic",
    ppns = "poppins_regular",
    ppns_semi_bl = "poppins_semi_bold",
    ppns_semi_bl_it = "poppins_semi_bold_italic",
    ppns_th = "poppins_thin",
    ppns_th_it = "poppins_thin_italic",

    dela = "dela",
}